### PR TITLE
Only use last line as fileName when packing

### LINKED ISSUE #114: Running script in prepack fails the packing process
I am trying to run a script in `prepack`, but it causes the output to be [more than only the filename](https://github.com/0x80/isolate-package/blob/main/src/lib/utils/pack.ts#L51) and therefore fails because it cannot find the packed file.

### PR DESCRIPTION
**Pull request by hjellek**
Fixes #114

### CODE REVIEW

File: src/lib/utils/pack.ts [hunk 1]
```diff
@@ -48,7 +48,8 @@ export async function pack(srcDir: string, dstDir: string) {
         );
       });
 
-  const fileName = path.basename(stdout.trim());
+  const lastLine = stdout.trim().split("\n").pop() || "";
```
Comment (0x80) [inline src/lib/utils/pack.ts]: I think it would be better to throw a descriptive error if lastLine is undefined, don't you think? Maybe even add the stdout to the message, like `Failed to parse last line from stdout: ${stdout.trim()}`

If basename can't parse the empty string, or if fileName becomes an empty string, the resulting error might not be so obvious.

Also, I have a slight preference for `at(-1)` instead of `pop()`, but that's nitpicking :)

**Review by 0x80 — CHANGES_REQUESTED** [review]
See comment...

File: src/lib/utils/pack.ts (hunk 1 above)
Comment (hjellek) [reply src/lib/utils/pack.ts]: Agreed, updated now!

File: src/lib/utils/pack.ts [hunk 2]
```diff
@@ -48,7 +48,13 @@ export async function pack(srcDir: string, dstDir: string) {
         );
       });
 
-  const lastLine = stdout.trim().split("\n").pop() || "";
+  const lastLine = stdout.trim().split("\n").at(-1)
+  if (!lastLine) {
+    log.error(
+      `Failed to parse last line from stdout: ${stdout.trim()}`
+    );
+    throw new Error("Unable to find fileName from pack output");
```
Comment (0x80) [inline src/lib/utils/pack.ts]: I don't see a need to log and throw, as the thrown error message should appear anyway. 

Please throw the message from log.error, as it is more informative.

**Review by 0x80 — CHANGES_REQUESTED** [review]

File: src/lib/utils/pack.ts (hunk 2 above)
Comment (hjellek) [reply src/lib/utils/pack.ts]: Not sure I understand exactly what you want me to do - only log, or only throw?

Comment (0x80) [reply src/lib/utils/pack.ts]: Only throw, but throw an error with the message that you currently use in log.error. Thanks!

Comment (0x80) [reply src/lib/utils/pack.ts]: ... unless you can convince me that logging + throwing has a clear benefit. I never do that myself(*), but that doesn't mean I'm right necessarily ;) 

(*) Unless the thrown error ends up being visible to the end-user and the system needs to log more/sensitive information internally.

Comment (hjellek) [reply src/lib/utils/pack.ts]: Gotcha, updated!

Well, I guess it depends on the error and log handling in general so I just did it both 😅
As you say, sometimes the error is shown to the user and the log message can contain more useful stuff for debugging.

**Review by 0x80 — APPROVED** [review]

File: src/lib/utils/pack.ts (hunk 2 above)
Comment (0x80) [reply src/lib/utils/pack.ts]: Please run prettier (pnpm format) to make the checks pass, then I can merge it...

Comment (hjellek) [reply src/lib/utils/pack.ts]: Done!

And thank you for your swift response, and efforts on the library in general 😊

**Comment by 0x80** [comment]
@hjellek I've published it under @next. Maybe you can give it a try and confirm that it works for you? 

I will include it in firebase-tools-with-isolate when a new minor version of that the upstream firebase-tools comes out.

**Comment by hjellek** [comment]
> @hjellek I've published it under @next. Maybe you can give it a try and confirm that it works for you?
> 

I'll be happy to test, but I can't find a branch or tag called `next` now?

**Comment by 0x80** [comment]
@hjellek It's available on npm under @next. So something like `pnpm add isolate-package@next -D` should work
